name: Build and Publish Image
description: Steps for building an image for a specific ruby version
inputs:
  ruby_version:
    required: true
  image_tag:
    required: true
  gh_token:
    required: true
  repository_owner:
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout (GitHub)
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.image_tag }}

    - name: Set up QEMU for multi-architecture builds
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64

    - name: Set Image version env variable
      run: echo "IMAGE_VERSION=$(echo ${{ inputs.image_tag }} | tr -d ruby-)" >> $GITHUB_ENV
      shell: bash

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.repository_owner }}
        password: ${{ inputs.gh_token }}

    - name: Pre-build Dev Container Image
      uses: devcontainers/ci@v0.3
      env:
        RUBY_VERSION: ${{ inputs.ruby_version }}
        BUILDX_NO_DEFAULT_ATTESTATIONS: true
      with:
        imageName: ghcr.io/bloomedai/devcontainer/images/ruby
        imageTag: ${{ env.IMAGE_VERSION }}-${{ inputs.ruby_version }},${{ inputs.ruby_version }}
        subFolder: images/ruby
        push: always
        platform: linux/amd64,linux/arm64

    - name: Checkout (GitHub)
      uses: actions/checkout@v4
